name: "kubewarden-policy-gh-action-dependencies"
description: "Install all the binaries needed inside of GH action"
branding:
  icon: "package"
  color: "blue"
runs:
  using: "composite"
  steps:
    - name: Install cosign
      uses: sigstore/cosign-installer@cad07c2e89fa2edd6e2d7bab4c1aa38e53f76003 # v4.1.1
    - name: Install kwctl
      shell: bash
      run: |
        #!/bin/bash
        set -e

        KWCTL_VERSION="v1.33.1"
        KWCTL_CHECKSUM="b1f0b18a9f538bba7677f32832bfd964eceefca8cdf8e9e9ecaa5398655d2c49"
        ASSET="kwctl-linux-x86_64"
        INSTALL_DIR=$HOME/.kwctl

        mkdir -p $INSTALL_DIR
        curl -sL https://github.com/kubewarden/kubewarden-controller/releases/download/${KWCTL_VERSION}/$ASSET.zip -o $INSTALL_DIR/$ASSET.zip
        echo "${KWCTL_CHECKSUM}  $INSTALL_DIR/$ASSET.zip" | sha256sum -c -
        unzip -o $INSTALL_DIR/$ASSET.zip -d $INSTALL_DIR
        rm $INSTALL_DIR/$ASSET.zip

        mv $INSTALL_DIR/$ASSET $INSTALL_DIR/kwctl
        chmod 755 $INSTALL_DIR/kwctl
        echo $INSTALL_DIR >> $GITHUB_PATH

        $INSTALL_DIR/kwctl -V
    - name: Install bats
      shell: bash
      run: sudo apt install -y bats
    - name: Install SBOM generator tool
      shell: bash
      run: |
        #!/bin/bash
        set -e

        SYFT_VERSION="1.28.0"
        SYFT_CHECKSUM="3edee7fe1ceb1f78360e547f57048930d57f00c7ec3d0b8bdfb902805f048468"
        INSTALL_DIR=$HOME/.syft

        mkdir -p $INSTALL_DIR

        curl -sL https://github.com/anchore/syft/releases/download/v${SYFT_VERSION}/syft_${SYFT_VERSION}_linux_amd64.tar.gz -o $INSTALL_DIR/syft.tar.gz
        echo "${SYFT_CHECKSUM}  $INSTALL_DIR/syft.tar.gz" | sha256sum -c -
        tar xvf $INSTALL_DIR/syft.tar.gz -C $INSTALL_DIR
        rm $INSTALL_DIR/syft.tar.gz

        echo $INSTALL_DIR >> $GITHUB_PATH
    - name: Install binaryen tool
      shell: bash
      run: |
        #!/bin/bash
        set -e

        BINARYEN_VERSION="116"
        BINARYEN_CHECKSUM="c55b74f3109cdae97490faf089b0286d3bba926bb6ea5ed00c8c784fc53718fd"
        INSTALL_DIR=$HOME/.binaryen

        mkdir -p $INSTALL_DIR

        curl -sL https://github.com/WebAssembly/binaryen/releases/download/version_${BINARYEN_VERSION}/binaryen-version_${BINARYEN_VERSION}-x86_64-linux.tar.gz -o $INSTALL_DIR/binaryen.tar.gz
        echo "${BINARYEN_CHECKSUM}  $INSTALL_DIR/binaryen.tar.gz" | sha256sum -c -
        tar xvf $INSTALL_DIR/binaryen.tar.gz -C $INSTALL_DIR
        mv $INSTALL_DIR/binaryen-version_${BINARYEN_VERSION}/bin/* $INSTALL_DIR
        rm $INSTALL_DIR/binaryen.tar.gz
        rm -rf $INSTALL_DIR/binaryen-version_${BINARYEN_VERSION}

        echo $INSTALL_DIR >> $GITHUB_PATH
    - name: Setup rust toolchain
      run: |
        rustup toolchain install stable --profile minimal --target wasm32-wasip1
        rustup override set stable
      shell: bash
    - name: Install tinygo
      shell: bash
      run: |
        set -e
        TINYGO_VERSION="0.39.0"
        TINYGO_CHECKSUM="775f15974e35059c8f3a141266bd9d293b5d556a3e44d5e6356c5602e9f386ab"
        TINYGO_DEB="tinygo_${TINYGO_VERSION}_amd64.deb"
        wget https://github.com/tinygo-org/tinygo/releases/download/v${TINYGO_VERSION}/${TINYGO_DEB}
        echo "${TINYGO_CHECKSUM}  ${TINYGO_DEB}" | sha256sum -c -
        sudo dpkg -i ${TINYGO_DEB}
        rm ${TINYGO_DEB}
    - name: Install semver tool
      shell: bash
      run: |
        SEMVER_VERSION="3.4.0"
        INSTALL_DIR="$HOME"/.semver
        mkdir -p "$INSTALL_DIR"
        wget -O "$INSTALL_DIR"/semver https://github.com/fsaintjacques/semver-tool/raw/837ad91179c4126e3b7ff73c35091d5ef561d9a3/src/semver
        chmod +x "$INSTALL_DIR"/semver
        echo "$INSTALL_DIR" >> "$GITHUB_PATH"
    - name: Install updatecli
      uses: updatecli/updatecli-action@2c3221bc5f4499a99fec2c87d9de4a83cb30e990 # v3.1.3
    - name: Install OPA
      shell: bash
      run: |
        set -e
        OPA_VERSION="v0.65.0"
        OPA_CHECKSUM="cd6b0b2d762571a746f0261890b155e6dd71cca90dad6b42b6fcf6dd7f619f08"
        INSTALL_DIR=$HOME/.opa
        mkdir -p $INSTALL_DIR
        curl -sL https://github.com/open-policy-agent/opa/releases/download/${OPA_VERSION}/opa_linux_amd64_static -o $INSTALL_DIR/opa
        echo "${OPA_CHECKSUM}  $INSTALL_DIR/opa" | sha256sum -c -
        chmod 755 $INSTALL_DIR/opa
        echo $INSTALL_DIR >> $GITHUB_PATH
