on:
  schedule:
    - cron: "30 3 12 * *" # At 03:30 on day-of-month 12
  workflow_dispatch:
    inputs:
      policy-working-dir:
        description: |
          Policy directory under policies folder. 
          Keep empty to release all policies
        required: false
        type: string
        default: ""
      policy-version:
        description: |
          Release version of the policy, without 'v' prefix. Optional.
          Defaults to extracting the version from tag if tag present.
          E.g: tag "v0.1.0", policy-version=0.1.0
        required: false
        type: string
        default: ""

name: Trigger policy release

jobs:
  calculate-policy-matrix:
    runs-on: ubuntu-latest
    outputs:
      policy_working_dirs: ${{ steps.calculate-policy-dirs.outputs.policy_working_dirs }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # checkout all history to do git diff
      - name: calculate which policies need a CI job
        id: calculate-policy-dirs
        shell: bash
        run: |
          if [ -z "${{inputs.policy-working-dir}}" ]; then
            # All policies must be released (scheduled run or workflow_dispatch with no specific policy)
            git remote -v
            policies_working_dirs=($(find policies -maxdepth 2 -name Makefile -exec dirname '{}' \;))

            declare -p policies_working_dirs # for debug
            policy_working_dirs=$(jq --compact-output --null-input \
              '$ARGS.positional | unique' \
              --args -- "${policies_working_dirs[@]}")
          else
            policy_working_dir=policies/${{ inputs.policy-working-dir }}
            if [ ! -d "$policy_working_dir" ]; then
              echo "$policy_working_dir does not exist"
              echo "::error title=Invalid inputs::$policy_working_dir does not exist"
              exit 1;
            fi
            # Release a single policy 
            policies_working_dirs=("policies/${{ inputs.policy-working-dir }}")
            declare -p policies_working_dirs # for debug
            policy_working_dirs=$(jq --compact-output --null-input '$ARGS.positional | unique' --args -- "${policies_working_dirs[@]}")
          fi

          echo "policy_working_dirs=$policy_working_dirs"
          echo "policy_working_dirs=$policy_working_dirs" >> $GITHUB_OUTPUT

  open-release-pr:
    name: "Open PR to release policy"
    runs-on: ubuntu-latest
    needs: calculate-policy-matrix
    strategy:
      fail-fast: false
      # limit the number of jobs to avoid rate limits errors from Github API
      max-parallel: 5
      matrix:
        policy-working-dir: ${{ fromJSON(needs.calculate-policy-matrix.outputs.policy_working_dirs) }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Install cargo-set-version
        run: cargo install cargo-edit --version 0.13.9 --locked

      - name: Get policy metadata
        id: policy-info
        uses: ./.github/actions/get-policy-metadata
        with:
          policy-working-dir: "${{ matrix.policy-working-dir }}"

      - name: Check if there is a tag to the version from metadata file.
        id: get-expected-version
        shell: bash
        run: |
          if [ ! -z "${{ inputs.policy-version }}" ]; then
            semver_result=$(semver compare ${{ steps.policy-info.outputs.policy-version }} ${{ inputs.policy-version }}) 
            if [ "$semver_result" == "1" ]; then
              echo "::error title=Invalid version::Cannot downgrade a policy version"
              exit 1
            fi
            echo "version=${{ inputs.policy-version }}" >> $GITHUB_OUTPUT
            exit 0
          fi
          # If there is no tag with the current version in the metadata file,
          # the previous version of the policy is missing. It looks like that
          # the policy is bein released for the first time. Then, release
          # drafter should use the current version already set in the policy.
          # Otherwise, let's release-drafter calculate the version for us based
          # on the PRs merged.
          policy_tag=$(git tag -l  $(basename ${{ matrix.policy-working-dir }})/v${{ steps.policy-info.outputs.policy-version }})
          if [ -z "$policy_tag" ]; then
            # No tag, let's use the version from the policy
            echo "version=${{ steps.policy-info.outputs.policy-version }}" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "version=''" >> $GITHUB_OUTPUT

      - name: Create draft release and calculate version
        id: create-release
        uses: release-drafter/release-drafter@563bf132657a13ded0b01fcb723c5a58cdd824e2 # v7.2.1
        with:
          config-name: "release-drafter-${{ steps.policy-info.outputs.policy-basename }}.yml"
          version: ${{ steps.get-expected-version.outputs.version}}
          token: ${{ steps.generate-token.outputs.token }}

      - name: Ensure that release drafter is not downgrading the policy version
        run: |
          semver_result=$(semver compare ${{ steps.policy-info.outputs.policy-version }} ${{ steps.create-release.outputs.resolved_version }}) 
          if [ "$semver_result" == "1" ]; then
            echo "::error title=Invalid version::Cannot downgrade a policy version"
            exit 1
          fi

      # If there is version lacking a tag, we do not need to run updatecli because
      # the script will not update the metadata.yaml file. Therefore, the tag
      # is the only thing missing
      - name: Trigger tagging workflow
        if: ${{ steps.get-expected-version.outputs.version == steps.policy-info.outputs.policy-version }}
        run: gh workflow run release-tag.yaml --field  "policy-working-dir=${{matrix.policy-working-dir }}"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Create values.yaml for Updatecli based on release drafter release and policy information
        if: ${{ steps.get-expected-version.outputs.version != steps.policy-info.outputs.policy-version }}
        run: |
          cat <<EOF > values.yaml
          github:
            owner: "${{ github.repository_owner }}"
            repo: "${{ github.event.repository.name }}"
          policy:
            version: "${{ steps.create-release.outputs.resolved_version}}"
            working_dir: "${{ matrix.policy-working-dir }}"
            rust_package: "${{ steps.policy-info.outputs.policy-rust-package }}"
          EOF

      - name: Open PR with updatecli
        if: ${{ steps.get-expected-version.outputs.version != steps.policy-info.outputs.policy-version }}
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |-
          updatecli apply --config updatecli/updatecli.d/open-release-pr.yaml \
            --values updatecli/values.yaml \
            --values $(pwd)/values.yaml
